library/urls.py
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='books'),
    path('search/', views.search_books, name='search'),
    path('book/<int:id>/', views.book, name='book'),
    path('author/<int:id>/', views.author, name='author'),
    path('authors/', views.authors, name='authors'),
    path('authors/search/', views.search_authors, name='search_authors'),
    path('borrow/', views.borrow, name='borrow'),
    path('borrowing-queue/', views.borrowing_queue, name='borrowing_queue'),
    path('borrowings', views.user_borrowings, name='borrowings'),
]

minhoteca/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('books/', include('library.urls', namespace='library')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

library/forms.py
from datetime import datetime, timedelta
from django import forms
from django.forms.models import ModelForm
from django.contrib.auth import get_user_model
from .models import Borrowing, Book


def _get_saturdays():
    """Retorna lista de sábados."""
    saturday_list = []
    today = datetime.now()
    weekday = today.weekday()
    new_day = None
    if weekday == 5:
        new_day = today + timedelta(days=7)
    elif weekday == 6:
        new_day = today + timedelta(days=6)
    else:
        new_day = today + timedelta(days=(5 - weekday))

    if new_day:
        saturday_list.append((new_day.strftime('%d/%m/%Y'), new_day.date()))
        new_day = saturday_list[0][1] + timedelta(days=7)
        saturday_list.append((new_day.strftime('%d/%m/%Y'), new_day))

    return saturday_list

class BorrowingForm(ModelForm):
    saturdays = _get_saturdays()
    date_borrowed = forms.ChoiceField(
            choices=saturdays,
            label='Escolha uma data',
            label_suffix = ": ",
            required = True,
            disabled = False,
            widget=forms.Select(
                attrs={
                    'class': 'form-select',
                    'aria-label': 'Selecione uma data'
                    }))
    borrower_id = forms.CharField(widget=forms.HiddenInput)
    book_id = forms.CharField(widget=forms.HiddenInput)
    schedule = forms.ChoiceField(
            choices=[
                ('08:00', datetime(2022,1,1,8,0).time()),
                ('09:00', datetime(2022,1,1,9,0).time()),
                ('14:00', datetime(2022,1,1,14,0).time()),
                ('15:00', datetime(2022,1,1,15,0).time()),
                ('16:00', datetime(2022,1,1,16,0).time())
                ],
            label='Escolha um horário',
            label_suffix = ": ",
            required = True,
            disabled = False,
            widget=forms.RadioSelect(
                attrs={'class': 'form-check-input mx-2'}
            )
    )

    class Meta:
        model = Borrowing
        fields = ['book_id', 'date_borrowed', 'borrower_id', 'schedule']

    def clean(self):
        cleaned_data = super().clean()
        date_borrowed = datetime.strptime(
                        cleaned_data.get('date_borrowed'),
                        '%d/%m/%Y')
        date_returned = cleaned_data.get('date_returned')
        if date_returned is not None and date_borrowed < date_returned:
            raise forms.ValidationError(
                'Date borrowed must be before date returned')
            
    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.date_borrowed = self.cleaned_data.get('date_borrowed')
        instance.borrower = get_user_model().objects.get(
            id=self.cleaned_data.get('borrower_id'))
        instance.book = Book.objects.get(id=self.cleaned_data.get('book_id'))
        instance.schedule = self.cleaned_data.get('schedule')
        if commit:
            instance.save()

        return instance

library/views.py
from datetime import datetime, timedelta
import operator
import json
import logging
import environ
from django.utils.html import strip_tags
from django.db.models import Max
from django.core import mail
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Value  # , Q
from django.db.models.functions import Concat
from django.contrib import messages
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.storage import staticfiles_storage

from accounts.models import MinhotecaUser
from .models import Book, Author, Borrowing, QueueBorrowing
from .forms import BorrowingForm

env = environ.Env()
environ.Env.read_env()
log = logging.getLogger()
log.setLevel(logging.INFO)

url = staticfiles_storage.path('data/countries.json')
countries = []
try:
    with open(url, "r", encoding='utf-8') as cdata:
        CONTENT = ''.join(cdata.readlines())
        countries = json.loads(CONTENT)
        countries = list(filter(lambda x: 'pt-br' in x, countries))
except Exception as ex:
    pass


@login_required(login_url='/accounts/login/')
def index(request):
    """Retorna os livros cadastrados."""
    order = request.GET.get('ord')
    if order and order == '2':
        books = Book.objects.order_by('-title').filter(is_available=True)
    elif order and order == '3':
        books = Book.objects.order_by('author__name').filter(is_available=True)
    elif order and order == '4':
        books = Book.objects.order_by('-author__name').filter(is_available=True)
    else:
        books = Book.objects.order_by('title').filter(is_available=True)
    paginator = Paginator(books, 20)
    pg = request.GET.get('pg')
    books = paginator.get_page(pg)
    classifications = [
        {'id': '1', 'description': 'Título de A - Z'},
        {'id': '2', 'description': 'Título de Z - A'},
        {'id': '3', 'description': 'Autor de A - Z'},
        {'id': '4', 'description': 'Autor de Z - A'}
    ]
    return render(request, 'library.html',
                  {'books': books, 'classifications': classifications})

@login_required(login_url='/accounts/login/')
def search_books(request):
    """Retorna o resultado de uma busca por livros."""
    try:
        expression = request.GET.get('term_search')
        if not expression:
            messages.add_message(
                request, messages.ERROR, 'Informe um valor para a busca.')
            return redirect('library:books')

        fields = Concat('title', Value(' '), 'subtitle',
                        Value(' '), 'author__name')
        books = Book.objects.annotate(
            title_subtitle=fields
        ).filter(
            title_subtitle__icontains=expression,
            is_available=True
        )
        if not books or len(books) == 0:
            messages.add_message(
                request, messages.WARNING,
                'Nenhum livro encontrado com o termo solicitado.')
            return redirect('library:books')

        order = request.GET.get('ord')
        if order and order == '2':
            sorted_list = sorted(
                books, key=operator.attrgetter('title'), reverse=True)
        elif order and order == '3':
            sorted_list = sorted(
                books, key=operator.attrgetter('author.name'))
        elif order and order == '4':
            sorted_list = sorted(
                books, key=operator.attrgetter('author.name'), reverse=True)
        else:
            sorted_list = sorted(books, key=operator.attrgetter('title'))

        paginator = Paginator(sorted_list, 10)
        pg = request.GET.get('pg')
        books = paginator.get_page(pg)
        classifications = [
            {'id': '1', 'description': 'Título de A - Z'},
            {'id': '2', 'description': 'Título de Z - A'},
            {'id': '3', 'description': 'Autor de A - Z'},
            {'id': '4', 'description': 'Autor de Z - A'}
        ]
        return render(request, 'library.html',
                      {'books': books, 'classifications': classifications})
    except Book.DoesNotExist:
        raise Http404()

@login_required(login_url='/accounts/login/')
def book(request, id:int):
    """Retorna os dados livro solicitado."""
    try:
        book_item = Book.objects.get(id=id)
        if not book_item.is_available:
            raise Http404()
        return render(request, 'book.html',
                      {'book': book_item})
    except Book.DoesNotExist:
        raise Http404()

@login_required(login_url='/accounts/login/')
def author(request, id:int):
    author_item = get_object_or_404(Author, id=id)
    books = author_item.book_set.filter(author_id=id,
                                    is_available=True)
    dic_author = {'author': author_item}
    country = next(filter(
        lambda x: x['pt-br'] == author_item.country, countries), None)
    if country:
        flag = f'data:image/png;base64, {country["flag"]}'
        dic_author.update({'flag': flag})
    else:
        dic_author.update({'flag': ''})

    return render(request, 'author.html',
                  {'author': dic_author, 'books': books})

@login_required(login_url='/accounts/login/')
def authors(request):
    """Lista autores cadastrados."""
    order = request.GET.get('ord')
    authors_data = Author.objects.order_by('name')\
        .filter(book__is_available=True)
    authors_data = set(authors_data)
    if order and order == '2':
        ordered_list = sorted(
            authors_data, key=operator.attrgetter('name'), reverse=True)
    elif order and order == '3':
        ordered_list = sorted(
            authors_data, key=operator.methodcaller('count_books'), reverse=True)
    elif order and order == '4':
        ordered_list = sorted(
            authors_data, key=operator.methodcaller('count_books'))
    else:
        ordered_list = sorted(authors_data, key=operator.attrgetter('name'))

    authors_list = []
    for author_item in ordered_list:
        dic_autor = {'author': author_item}
        country = next(filter(
            lambda x: x['pt-br'] == author_item.country, countries), None)
        if country:
            flag = f'data:image/png;base64, {country["flag"]}'
            dic_autor.update({'flag': flag})
        else:
            dic_autor.update({'flag': ''})
        authors_list.append(dic_autor)
    paginator = Paginator(authors_list, 20)
    pg = request.GET.get('pg')
    authors_data = paginator.get_page(pg)
    classifications = [
        {'id': '1', 'description': 'Nome de A - Z'},
        {'id': '2', 'description': 'Nome de Z - A'},
        {'id': '3', 'description': 'Mais livros'},
        {'id': '4', 'description': 'Menos livros'}
    ]
    return render(request, 'authors.html',
                  {'authors': authors_data, 'classifications': classifications})

@login_required(login_url='/accounts/login/')
def search_authors(request):
    """Retorna o resultado de uma busca por autores."""
    try:
        expression = request.GET.get('term_search')
        if not expression:
            messages.add_message(
                request, messages.ERROR, 'Informe um valor para a busca.')
            return redirect('library:authors')

        fields = Concat('name', Value(' '), 'country')
        authors_data = Author.objects.order_by('name')\
            .annotate(author_country=fields).filter(
                author_country__icontains=expression,
                book__is_available=True)
        authors_data = set(authors_data)
        if not authors_data or not len(authors_data):
            messages.add_message(
                request, messages.WARNING,
                'Nenhum autor encontrado com o termo solicitado.')
            return redirect('library:authors')

        order = request.GET.get('ord')
        if order and order == '2':
            ordered_list = sorted(
                authors_data, key=operator.attrgetter('name'), reverse=True)
        elif order and order == '3':
            ordered_list = sorted(
                authors_data, key=operator.methodcaller('count_books'),
                reverse=True)
        elif order and order == '4':
            ordered_list = sorted(
                authors_data, key=operator.methodcaller('count_books'))
        else:
            ordered_list = sorted(authors_data, key=operator.attrgetter('name'))

        authors_list = []
        for author_item in ordered_list:
            dic_autor = {'author': author_item}
            country = next(filter(
                lambda x: x['pt-br'] == author_item.country, countries), None)
            if country:
                flag = f'data:image/png;base64, {country["flag"]}'
                dic_autor.update({'flag': flag})
            else:
                dic_autor.update({'flag': ''})
            authors_list.append(dic_autor)
        paginator = Paginator(authors_list, 20)
        pg = request.GET.get('pg')
        authors_data = paginator.get_page(pg)
        classifications = [
            {'id': '1', 'description': 'Nome de A - Z'},
            {'id': '2', 'description': 'Nome de Z - A'},
            {'id': '3', 'description': 'Mais livros'},
            {'id': '4', 'description': 'Menos livros'}
        ]
        return render(request, 'authors.html',
                      {'authors': authors_data, 'classifications': classifications})
    except Author.DoesNotExist:
        raise Http404()

def _request_borrowing(request):
    borrower = request.user
    borrowed = Borrowing.objects.filter(
        borrower=borrower,date_returned=None).first()
    if borrowed:
        return render(request, 'borrow.html', {'borrowed': borrowed})

    book_id = request.GET.get('book')
    if not book_id:
        messages.add_message(

library/templates/author.html
{% extends 'base.html' %}

{% block title %}{{author.author.name}}{% endblock %}

{% block content %}
<section class="exemplar">
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            <h4 class="card-title">{{author.author.name}}</h4>
        </div>
        <div class="card-body">
            <img src="{{ author.author.picture_url }}" alt="{{ author.author.name }}" class="card-img" />
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col col-4">
                    {% if author.flag %}
                    <img class="icone" src="{{author.flag}}" alt="{{ author.author.country }}"
                        title="{{ author.author.country }}" />
                    {% else %}
                    <span class="text-muted">{{ author.author.country }}</span>
                    {% endif %}
                </div>

                <div class="col col-4">
                    <i class="fa-solid fa-book"></i>{{ author.author.count_books }}
                </div>
                <div class="col col-4">
                    <a href="{{ author.author.wikipedia|default_if_none:"#" }}" target="_blank"
                        class="card-link autor-link">
                        <i class="fa-regular fa-address-card"></i>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="book-list">
        {% if books %}
        <h3>Livros</h3>
        <ul class="list-group list-group-flush">
            {% for book in books %}
            <li class="list-group-item list-group-item-action">
                <a href="{% url 'library:book' book.id %}" class="">
                    {{book.title}}<br />
                    {% if book.subtitle %}
                    <small>
                        {{ book.subtitle }}
                    </small>
                    {% endif %}
                </a>
            </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>

</section>
{% endblock %}

library/templates/authors.html
{% extends 'base.html' %}
{% block title %}Autores{% endblock %}
{% load static %}
{% block content %}
<div class="container">
    {% include "nav_header.html" with titulo="Autores" classificacao=True classificacoes=classifications filters=True paginacao=True placeholder="Pesquise por nome, sobrenome ou país" navegador=autores search_url="search" %}
    <section id="autores" class="d-flex flex-row flex-wrap justify-content-around p-3">
        {% for author in authors %}
        <div class="card autor mx-2 mb-4 w-25">
            <div class="card-header">
                <h5 class="card-title">{{author.author.name}}</h5>
            </div>
            <div class="card-body">
                {% if author.author.picture_url %}
                <img src="{{ author.author.picture_url }}" alt="{{ author.author.name }}" class="w-100" />
                {% else %}
                <img src="{% static 'imgs/blank-profile-picture-973460.svg'%}" alt="{{ author.author.name }}"
                    class="w-100" />
                {% endif %}
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col col-4">
                        {% if author.flag %}
                        <img class="icone" src="{{author.flag}}" alt="{{ author.author.country }}"
                            title="{{ author.author.country }}" />
                        {% else %}
                        <span class="text-muted">{{ author.author.country }}</span>
                        {% endif %}
                    </div>
                    <div class="col col-4">
                        <a href="{% url 'library:author' author.author.id %}" class="card-link autor-link">
                            <i class="fa-solid fa-book"></i>{{ author.author.count_books }}
                        </a>
                    </div>
                    <div class="col col-4">
                        <a href="{{ author.author.wikipedia|default_if_none:"#" }}" target="_blank"
                            class="card-link autor-link">
                            <i class="fa-regular fa-address-card"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </section>
    {% include 'nav_footer.html' with navegador=authors %}
</div>
{% endblock %}

library/templates/book.html
{% extends 'base.html' %}

{% block title %}{{book.title}}{% endblock %}

{% block content %}
<section class="exemplar">
    <div class="card" style="width: 18rem;">
        <div class="card-header">
            <h4 class="card-title">{{ book.title }}</h4>
            {% if book.subtitle %}
            <h6 class="card-subtitle mb-2 text-muted">{{ book.subtitle|default_if_none:""}}</h6>
            {% endif %}
        </div>
        <div class="card-body">
            <img class="card-img" src="{{ book.picture_url }}" alt="{{ book.title }}">
        </div>
        <div class="card-footer">
            <div class="row">
                <div class="col col-12 text-muted">
                    <i class="fa-solid fa-language"></i>
                    {{ book.language }}
                </div>
            </div>
            <div class="row">
                <div class="col col-12">
                    <i class="fa-solid fa-feather-pointed"></i>
                    <a href="{% url 'library:author' book.author_id %}" class="card-link">{{ book.author }}</a>
                </div>
            </div>
            <div class="row">
                <div class="col col-12">
                    <i class="fa-solid fa-print"></i>
                    <a href="{{ book.publisher__website }}" class="card-link">{{ book.publisher }}</a>
                </div>
            </div>
        </div>
    </div>

    <div class="synopsis">
        {{ book.synopsis }}
        <footer class="row">
            <div class="col col-12">
                {% if not book.borrowed %}
                <a href="{% url 'library:borrow' %}?book={{book.id}}" class="card-link text-success"
                    title="Solicitar empréstimo">
                    <i class="fas fa-book"></i> Solicitar empréstimo
                </a>
                {% else %}
                <a href="#" class="card-link text-warning" title="Pedir para ser o próximo">
                    <i class="fas fa-hand-paper"></i> Pedir para ser o próximo
                </a>
                {% endif %}
            </div>
        </footer>
    </div>

</section>
{% endblock %}

library/templates/library.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Livros Disponíveis{% endblock %}

{% block content %}

<section id="livros">
    {% include "nav_header.html" with titulo="Livros" classificacao=True classificacoes=classifications filters=True paginacao=True placeholder="Pesquise por título, subtítulo ou autor" navegador=livros search_url="search" %}

    <div class="table-responsive">
        <table class="table table-striped table-sm" id="books-list">
            <caption>Exibindo {{ books.start_index }}-{{ books.end_index }} de {{ books.paginator.count }} livros
                disponíveis</caption>
            <thead class="">
                <tr>
                    <th class="titulo">
                        <div class="d-flex justify-content-between">
                            <div class="">Título / Subtítulo</div>
                            <div class="">
                                {% if request.GET.ord and request.GET.ord == '2' %}
                                <span class="badge badge-info">
                                    <i class="fas fa-sort-alpha-up"></i>
                                </span>
                                {% elif not request.GET.ord or request.GET.ord == '1' %}
                                <span class="badge badge-secondary">
                                    <i class="fas fa-sort-alpha-down"></i>
                                </span>
                                {% endif %}
                            </div>
                        </div>
                    </th>
                    <th>
                        <div class="d-flex justify-content-between">
                            <div class="">Autor</div>
                            <div class="">
                                {% if request.GET.ord and request.GET.ord == '4' %}
                                <span class="badge badge-info">
                                    <i class="fas fa-sort-alpha-up"></i>
                                </span>
                                {% elif request.GET.ord and request.GET.ord == '3' %}
                                <span class="badge badge-secondary">
                                    <i class="fas fa-sort-alpha-down"></i>
                                </span>
                                {% endif %}
                            </div>
                        </div>
                    </th>
                    <th>Opções</th>
                </tr>
            </thead>
            <tbody>
                {% for book in books %}
                <tr class="{% if book.borrowed %}bg-secondary{% endif %}">
                    <td class="">
                        <a href="{% url 'library:book' book.id %}"
                            class="livro {% if book.borrowed %}text-light{% endif %}">
                            <h5 class="">{{ book.title }}
                                {% if book.subtitle %}
                                <small> - {{ book.subtitle }}</small>
                                {% endif %}
                            </h5>
                        </a>
                    </td>
                    <td>
                        <a href="{% url 'library:author' book.author_id %}"
                            class="{% if book.borrowed %}text-light{% endif %}">{{ book.author }}</a>
                    </td>
                    <td class="opcoes">
                        {% if not book.borrowed %}
                        <!-- <a href="{ % url 'loans:new' book.id %}" class="text-primary" title="Solicitar empréstimo"> -->
                        <a href="{% url 'library:borrow' %}?book={{book.id}}" title="Solicitar empréstimo"
                            class="disponivel">
                            <i class="fa-solid fa-handshake-simple"></i>
                        </a>
                        {% else %}
                        <!-- <a href="{ % url 'loans:reservation' book.id %}" class="text-light" title="Pedir para ser o próximo"> -->
                        <a href="{% url 'library:borrowing_queue' %}?book={{book.id}}" title="Pedir para ser o próximo"
                            class="emprestado">
                            <i class="fa-solid fa-person-walking"></i>
                        </a>
                        {% endif %}
                    </td>
                </tr>
                {% empty %}
                <tr colspan="3">Ainda não há livros cadastrados.</tr>
                {% endfor %}
            </tbody>
            <tfoot>
                {{ form.as_p }}
            </tfoot>
        </table>
    </div>
    {% include 'nav_footer.html' with navegador=books %}
</section>

{% endblock %}

library/templates/queue_borrowing.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Solicitação de Empréstimo{% endblock %}

{% block content %}

<div class="container justify-content-center mx-auto shadow p-4 w-75">
    {% if context %}
    <h4>Entre na fila!</h4>
    <p>Abaixo está a data de previsão para que você possa pegar o livro emprestado e quantas pessoas estão à sua frente
        na lista de espera.</p>

    <div class="row">
        <div class="col col-5">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <h4 class="card-title">{{ context.book.title }}</h4>
                    {% if context.book.subtitle %}
                    <h6 class="card-subtitle mb-2 text-muted">{{ context.book.subtitle|default_if_none:""}}</h6>
                    {% endif %}
                </div>
                <div class="card-body">
                    <img class="card-img" src="{{ context.book.picture_url }}" alt="{{ context.book.title }}">
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col col-12 text-muted">
                            <i class="fa-solid fa-language"></i>
                            {{ context.book.language }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12">
                            <i class="fa-solid fa-feather-pointed"></i>
                            <a href="{% url 'library:author' context.book.author_id %}"
                                class="card-link">{{ context.book.author }}</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12">
                            <i class="fa-solid fa-print"></i>
                            <a href="{{ context.book.publisher.website }}"
                                class="card-link">{{ context.book.publisher }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-7">
            <div class="row">
                <div class="col">
                    Pessoas à sua frente: <strong class="text-primary">{{context.members}}</strong>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    Data disponível para você: <strong
                        class="text-primary">{{context.next_date|date:"D d/M/Y"}}</strong>
                </div>
            </div>

            <div class="row mt-4">
                <div class="col col-12 text-center">
                    <h4>Deseja entrar na fila?</h4>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col col-12 text-center">
                    <form method="post">
                        <input type="hidden" name="book_id" id="book_id" value="{{ context.book.id }}" />
                        <input type="hidden" name="next_date" id="next_date"
                            value="{{context.next_date|date:"d/m/Y"}}" />
                        {% csrf_token %}
                        <input type="submit" value="Quero participar!" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% else %}
    {% if confirmation %}
    <div class="row">
        <div class="col col-5">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                    <h4 class="card-title">{{ confirmation.queue.book.title }}</h4>
                    {% if confirmation.queue.book.subtitle %}
                    <h6 class="card-subtitle mb-2 text-muted">{{ confirmation.queue.book.subtitle|default_if_none:""}}
                    </h6>
                    {% endif %}
                </div>
                <div class="card-body">
                    <img class="card-img" src="{{ confirmation.queue.book.picture_url }}"
                        alt="{{ confirmation.queue.book.title }}">
                </div>
                <div class="card-footer">
                    <div class="row">
                        <div class="col col-12 text-muted">
                            <i class="fa-solid fa-language"></i>
                            {{ confirmation.queue.book.language }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12">
                            <i class="fa-solid fa-feather-pointed"></i>
                            <a href="{% url 'library:author' confirmation.queue.book.author_id %}"
                                class="card-link">{{ confirmation.queue.book.author }}</a>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col col-12">
                            <i class="fa-solid fa-print"></i>
                            <a href="{{ context.book.publisher.website }}"
                                class="card-link">{{ confirmation.queue.book.publisher }}</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col col-7">
            <h4>Você está na fila!</h4>
            <div class="row mt-3">
                <div class="col">
                    A data prevista para seu empréstimo é {{ confirmation.queue.expected_date|date:"D d/M/Y" }}.
                </div>
            </div>
            <div class="row">
                <div class="col">
                    Você está na {{ confirmation.position }}ª posição na fila.
                </div>
            </div>
        </div>
    </div>
    {% endif %}
    {% endif %}
</div>
{% endblock %}