accounts/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, \
    PasswordResetDoneView, PasswordResetCompleteView #, PasswordChangeView
from .views import create_user, confirmation, logoff, get_profile,\
    edit_profile, ChangePasswordView, reset_password_confirm, reconfirmation


app_name = 'accounts'
urlpatterns = [
    path('', create_user, name='accounts'),
    path('create/', create_user, name='create_user'),
    path('confirmation/<uidb64>/<token>/', confirmation, name='confirmation'),
    path('reconfirmation/', reconfirmation, name='reconfirmation'),
    path('login/', LoginView.as_view(),
        {'template_name': 'accounts/login.html'}, name='login'),
    path('logout/', logoff, name='logout'),
    path('profile/', get_profile, name='profile'),
    path('edit_profile/', edit_profile, name='edit_profile'),
    path('change_password/', ChangePasswordView.as_view(), name='change_password'),
    path('reset_password/', PasswordResetView.as_view(
        success_url=reverse_lazy('accounts:password_reset_done'),
        email_template_name='emails/reset_password_email.html',
        template_name='reset_password.html',
        html_email_template_name='emails/reset_password_email.html',),
        name='reset_password'),
    path('password_reset_done/',PasswordResetDoneView.as_view(
        template_name='password_reset_done.html'),
        name='password_reset_done'),
    path('reset_password_complete/',PasswordResetCompleteView.as_view(
        template_name='reset_password_complete.html'),
        name='reset_password_complete'
    ),
    path('reset/<uidb64>/<token>/',
         reset_password_confirm,
         name='password_reset_confirm'),
]

library/urls.py
from django.urls import path
from . import views

app_name = 'library'

urlpatterns = [
    path('', views.index, name='books'),
    path('search/', views.search_books, name='search'),
    path('book/<int:id>/', views.book, name='book'),
    path('author/<int:id>/', views.author, name='author'),
    path('authors/', views.authors, name='authors'),
    path('authors/search/', views.search_authors, name='search_authors'),
    path('borrow/', views.borrow, name='borrow'),
    path('borrowing-queue/', views.borrowing_queue, name='borrowing_queue'),
    path('borrowings', views.user_borrowings, name='borrowings'),
]

minhoteca/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('books/', include('library.urls', namespace='library')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

accounts/forms.py
from django import forms
from django.forms.models import ModelForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model
from django.utils.safestring import mark_safe
from .models import MinhotecaUser as MinhotecaUser
# from captcha.fields import CaptchaField


class CreateUserForm(UserCreationForm):
    # recaptcha = CaptchaField()
    # site key = 6LfI738gAAAAADAs0ja5JcUFdzPT4yXViOXs5pUX
    # secret key = 6LfI738gAAAAAM6mEDXnCPNziPeBy8D_aaB4WT_m
    email = forms.EmailField(label='Email')
    user_term_accept = forms.BooleanField(
        required=True, label=mark_safe('Li e aceito os <a href="#">termos de uso</a>')
        )

    def save(self, commit=True):
        if not self.cleaned_data['user_term_accept']:
            raise forms.ValidationError(
                'Você precia ler e aceitar os termos de uso para continuar.')

        user = get_user_model().objects.create_user(
            email=self.cleaned_data['email'],
            password=self.cleaned_data['password1']
        )
        return user

    class Meta:
        model = MinhotecaUser
        fields = ['email','user_term_accept']

class UserProfileForm(ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    zip_code = forms.CharField(required=True, label='CEP')
    contact_phone = forms.CharField(max_length=11, label='Celular')
    address = forms.CharField(max_length=100, label='Endereço')
    address_number = forms.CharField(max_length=10, label='Número')
    address_complement = forms.CharField(max_length=50,
    label='Complemento', required=False)
    neighborhood = forms.CharField(max_length=50, label='Bairro')
    city = forms.CharField(max_length=50, label='Cidade')
    state = forms.CharField(max_length=2, label='UF')

    class Meta:
        model = MinhotecaUser
        # model.state = "SP"
        fields = ['first_name', 'last_name', 'contact_phone',
            'zip_code', 'address', 'address_number', 'city', 'state',
            'address_complement', 'neighborhood']

    def save(self, commit=True):
        user = MinhotecaUser.objects.get(id=self.cleaned_data['id'])
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.contact_phone = self.cleaned_data['contact_phone']
        user.zip_code = self.cleaned_data['zip_code']
        user.address = self.cleaned_data['address']
        user.address_number = self.cleaned_data['address_number']
        user.address_complement = self.cleaned_data['address_complement']
        user.neighborhood = self.cleaned_data['neighborhood']
        user.city = self.cleaned_data['city']
        user.state = self.cleaned_data['state']
        user.can_borrow = \
            len(user.first_name.strip()) > 0 and \
                len(user.contact_phone.strip()) > 0 and \
                    len(user.last_name.strip()) > 0 and \
                        len(user.zip_code.strip()) > 0 and \
                            len(user.address.strip()) > 0 and \
                                len(user.city.strip()) > 0 and \
                                    len(user.address_number.strip()) > 0 and \
                                        len(user.state.strip()) > 0
        if commit:
            user.save()

        return user


class PwdChangeForm(PasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['old_password'].widget.attrs['class'] = 'form-control'
        self.fields['new_password1'].widget.attrs['class'] = 'form-control'
        self.fields['new_password2'].widget.attrs['class'] = 'form-control'

accounts/views.py
import logging
from django.core import mail
from django.views import View
from django.urls import reverse
from django.utils.encoding import force_bytes, force_str
from django.utils.html import strip_tags
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.shortcuts import render, get_object_or_404, redirect
from django.template.loader import render_to_string
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages, auth
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import SetPasswordForm
import environ
import base64
from .tokens import account_activation_token
from .forms import CreateUserForm, UserProfileForm, PwdChangeForm
from .models import MinhotecaUser


env = environ.Env()
environ.Env.read_env()
log = logging.getLogger()
log.setLevel(logging.INFO)

def create_user(request):
    if request.method != 'POST':
        form = CreateUserForm()
        return render(request, 'account.html', {'form': form})

    form = CreateUserForm(request.POST)
    try:
        if form.is_valid():
            new_user = form.save()
            if new_user:
                current_site = get_current_site(request)
                subject = 'Confirme seu cadastro na Minhoteca'
                to_email = form.cleaned_data.get('email')
                message = render_to_string(
                    'emails/account_activation_email.html',
                    {
                        'user': new_user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(
                            force_bytes(new_user.pk)),
                        'token': account_activation_token.make_token(
                            new_user),
                    })
                plain_message=strip_tags(message)
                mail.send_mail(subject, plain_message,
                    from_email=env('DEFAULT_FROM_EMAIL'),
                    recipient_list=[to_email], html_message=message)
                admin_message = f"Novo usuário cadastrado: {new_user.email}"
                mail.send_mail("Novo usuário na minhoteca",
                    admin_message,
                    from_email=env('DEFAULT_FROM_EMAIL'),
                    recipient_list=[env('DEFAULT_FROM_EMAIL'),
                        "gustavo.adolfo.as@gmail.com"])
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    'Foi enviado um e-mail de confirmação com instruções para '+
                    'validar sua conta.<br/>Aguardo você em breve!',
                    extra_tags='success safe')
                messages.add_message(
                    request,
                    messages.INFO,
                    'Você só poderá solicitar empréstimos após ' +
                    'completar seu perfil e ter seu cadastro aprovado.',
                    extra_tags='info safe')
                return HttpResponseRedirect('/')

        return render(request, 'account.html', {'form': form})
    except Exception as error:
        log.error(error)
        messages.warning(
            request,
            ('Ocorreu uma falha ao realizar o cadastro. '+
            'Por favor tente novamente mais tarde.')
        )
        return render(request, 'account.html', {'form': form})

def reconfirmation(request):
    if request.method == 'GET':
        return render(request, 'reconfirmation.html')
    try:
        reconfirm_email = request.POST.get('email')
        new_user = MinhotecaUser.objects.get(email=reconfirm_email)
        current_site = get_current_site(request)
        subject = 'Confirme seu cadastro na Minhoteca'
        to_email = new_user.email
        message = render_to_string(
            'emails/account_activation_email.html',
            {
                'user': new_user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
                'token': account_activation_token.make_token(new_user),
            })
        plain_message=strip_tags(message)
        mail.send_mail(subject, plain_message,
            from_email=env('DEFAULT_FROM_EMAIL'),
            recipient_list=[to_email], html_message=message)

        admin_message = f"Novo usuário cadastrado: {new_user.email}"
        mail.send_mail("Novo usuário na minhoteca",
            admin_message, from_email=env('DEFAULT_FROM_EMAIL'),
            recipient_list=[env('DEFAULT_FROM_EMAIL'),
            "gustavo.adolfo.as@gmail.com"])

        messages.add_message(request, messages.SUCCESS,
            'Foi enviado um e-mail de confirmação com instruções para '+
            'validar sua conta.<br/>Aguardo você em breve!',
            extra_tags='success safe')
        messages.add_message(request, messages.INFO,
            'Você só poderá solicitar empréstimos após ' +
            'completar seu perfil e ter seu cadastro aprovado.',
            extra_tags='info safe')
        return HttpResponseRedirect('/')
    except Exception as error:
        log.error(error)
        messages.warning(request,
            ('Ocorreu uma falha ao tentar recuperar seu cadastro. '+
            'Por favor tente novamente mais tarde.'))


def confirmation(request, uidb64, token):
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = MinhotecaUser.objects.get(pk=uid)
    except: # (TypeError, ValueError, OverflowError): #MinhotecaUser.DoesNotExist
        user = None

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        messages.success(
            request, (
                'E-mail confirmado com sucesso. Faça login para continuar.'))
        return HttpResponseRedirect(reverse('accounts:login'))
    else:
        log.error(['Falha em confirmação de conta.', request, uidb64])
        messages.warning(
            request, (
                'O link de confirmação é inválido, possivelmente ' +
                'porque ele já pode ter sido utilizado ou não foi ' +
                'possível identificar a conta.'))
        return HttpResponseRedirect(reverse('accounts:create_user'))


def logoff(request):
    """Faz log out do usuário."""
    logout(request)
    request.session.flush()
    return HttpResponseRedirect('/')

def _get_profile_level(user):
    profile_complete = 8
    profile_weight = 0
    profile_weight += 1 if user.first_name else 0
    profile_weight += 1 if user.contact_phone else 0
    profile_weight += 1 if user.email else 0
    profile_weight += 1 if user.zip_code else 0
    profile_weight += 1 if user.address else 0
    profile_weight += 1 if user.city else 0
    profile_weight += 1 if user.address_number else 0
    profile_weight += 1 if user.state else 0
    return (100 * profile_weight) // profile_complete

@login_required(login_url='/accounts/login/')
def get_profile(request):
    """Mostra o perfil do usuário."""
    user = auth.get_user(request)
    try:
        user_profile = get_object_or_404(MinhotecaUser, id=user.id)
        profile_level = _get_profile_level(user_profile)
        profile_form = UserProfileForm(instance=user_profile)
        context = { 'profile_level': profile_level, 'profile_form': profile_form }
        return render(request, 'profile.html', context)
    except Exception as error:
        log.error(error)
        messages.warning(
            request,
            ('Ocorreu um erro ao carregar seu perfil. '+
            'Por favor tente novamente mais tarde.')
        )
        return HttpResponseRedirect('/')


def _update_profile(request, current_profile):
    profile_form = UserProfileForm(
        instance=current_profile,
        data=request.POST) #, files=request.FILES)
    if profile_form.is_valid():
        current_profile = profile_form.save(commit=False)
        current_profile.save()
        return None

    return profile_form

def _create_new_profile(request):
    profile_form = UserProfileForm(request.POST) #, request.FILES)
    if profile_form.is_valid():
        new_profile = profile_form.save(commit=False)
        new_profile.email = request.user.email
        new_profile.save()

@login_required(login_url='/accounts/login/')
def edit_profile(request):
    """Salvar o perfil do usuário."""
    if request.method != 'POST':
        return HttpResponseRedirect(reverse('accounts:profile'))
    
    user = auth.get_user(request)
    try:
        if MinhotecaUser.objects.filter(id=user.id).exists():
            profile = get_object_or_404(MinhotecaUser, id=user.id)
            update_form = _update_profile(request, profile)
            if not update_form:
                messages.add_message(request, messages.SUCCESS,
                                        'Perfil atualizado com sucesso!')
                return HttpResponseRedirect('/')
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    'Os dados informados não são válidos.')
                profile_form = UserProfileForm(request.POST) #, request.FILES)
                profile_level = _get_profile_level(profile)
                context = {
                    'profile_level': profile_level,
                    'profile_form': profile_form
                }
                return render(request, 'profile.html', context)
        else:
            _create_new_profile(request)
            mail.send_mail("Novo perfil pendente de aprovação",
                    f"Novo perfil pendente de aprovação: {user.email}",
                    from_email=env('DEFAULT_FROM_EMAIL'),
                    recipient_list=[env('DEFAULT_FROM_EMAIL'),

accounts/templates/account.html
{% extends 'base.html' %}

{% block title %}Minhoteca{% endblock %}

{% block content %}
<div class="container" id="front">
    <div class="row justify-content-md-center">
        <div class="col col-sm-12 col-md-8">
            {% include 'create_user.html' %}
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/confirmation.html
{% extends 'base.html' %}

{% block title %}Minhoteca{% endblock %}

{% block content %}
<div class="container" id="front">
    <div class="row justify-content-md-center">
        <div class="col col-sm-12 col-md-8" style="border: 1px solid blue">
            Confirmação
        </div>
    </div>
    <div class="row justify-content-md-center" style="border: 1px solid orangered">
        <div class="col col-12">
            Anúncios
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/profile.html
{% extends 'base.html' %}
{% block title %}Perfil do Usuário{% endblock %}
{% block content %}
<section id="profile-section" class="container">

    <header class="p-4 mb-4 border">
        <h1>Perfil de Usuário</h1>
        <p class="mb-4">Preencha os dados de perfil para que possamos formalizar os empréstimos
            podendo fazer a entrega e recuperação dos livros adequadamente.</p>

        <div class="row">
            <div class="col-12 col-md-8">
                <h6 class="">Força do perfil:</h6>
                <div class="progress bg-secondary">
                    <div class="progress-bar bg-primary" role="progressbar" style="width: {{profile_level}}%;"
                        aria-valuenow="{{profile_level}}%" aria-valuemin="0" aria-valuemax="100">{{profile_level}}%
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-4 text-end align-bottom align-text-bottom">
                <a href="{% url 'accounts:change_password' %}" class="btn btn-info btn-sm mt-2">Redefinir Senha</a>
            </div>
        </div>
    </header>

    <div class="p-4 mt-3 border">
        <p class="small">Reveja os <a href="#">termos de uso</a> e a <a href="#">política de privacidade</a>.</p>
        <form action="{% url 'accounts:edit_profile' %}" method="post">
            {% csrf_token %}

            <input type="hidden" name="{{profile_form.id.name}}" id="{{profile_form.id.name}}"
                value="{{ user.id|default_if_none:"" }}" />

            <!-- <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{profile_form.email.name}}">{{profile_form.email.label}}</label>
                        <input type="email" class="form-control
                        {% if profile_form.email.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.email.name}}" name="{{profile_form.email.name}}"
                            value="{{ profile_form.email.value|default_if_none:"" }}" disabled>
                        <span class="help-block
                        {% if profile_form.email.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.email.errors.0 }}</span>
                    </div>
                </div>
            </div> -->
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{profile_form.first_name.name}}">Nome</label>
                        <input type="text" class="form-control
                        {% if profile_form.first_name.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.first_name.name}}" name="{{profile_form.first_name.name}}"
                            value="{{ profile_form.first_name.value|default_if_none:"" }}">
                        {% if profile_form.first_name.errors %}
                        <span class="help-block
                        {% if profile_form.first_name.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.first_name.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="{{profile_form.last_name.name}}">Sobrenome</label>
                        <input type="text" class="form-control
                        {% if profile_form.last_name.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.last_name.name}}" name="{{profile_form.last_name.name}}"
                            value="{{ profile_form.last_name.value|default_if_none:"" }}">
                        {% if profile_form.last_name.errors %}
                        <span class="help-block
                        {% if profile_form.last_name.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.last_name.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6 col-md-2">
                    <div class=" form-group">
                        <label for=" {{profile_form.contact_phone.name}}">{{profile_form.contact_phone.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.contact_phone.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.contact_phone.name}}"
                            name="{{profile_form.contact_phone.name}}"
                            value="{{ profile_form.contact_phone.value|default_if_none:"" }}">
                        {% if profile_form.contact_phone.errors %}
                        <span class="help-block
                         {% if profile_form.contact_phone.errors %} text-danger small {% endif %}
                         ">{{ profile_form.contact_phone.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-6 col-md-2">
                    <div class="form-group">
                        <label for="{{profile_form.zip_code.name}}">{{profile_form.zip_code.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.zip_code.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.zip_code.name}}" name="{{profile_form.zip_code.name}}"
                            value="{{ profile_form.zip_code.value|default_if_none:"" }}">
                        {% if profile_form.zip_code.errors %}
                        <span class="help-block
                        {% if profile_form.zip_code.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.zip_code.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-md-6">
                    <div class="form-group">
                        <label for="{{profile_form.address.name}}">{{profile_form.address.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.address.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.address.name}}" name="{{profile_form.address.name}}"
                            value="{{ profile_form.address.value|default_if_none:"" }}">
                        {% if profile_form.address.errors %}
                        <span class="help-block
                        {% if profile_form.address.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.address.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-4 col-md-2">
                    <div class="form-group">
                        <label for="{{profile_form.address_number.name}}">{{profile_form.address_number.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.address_number.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.address_number.name}}"
                            name="{{profile_form.address_number.name}}"
                            value="{{ profile_form.address_number.value|default_if_none:"" }}">
                        {% if profile_form.address_number.errors %}
                        <span class="help-block
                        {% if profile_form.address_number.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.address_number.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="col-12 col-md-3">
                    <div class="form-group">
                        <label
                            for="{{profile_form.address_complement.name}}">{{profile_form.address_complement.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.address_complement.errors %}
                        border border-danger
                        {% endif %}" id="{{profile_form.address_complement.name}}"
                            name="{{profile_form.address_complement.name}}"
                            value="{{ profile_form.address_complement.value|default_if_none:"" }}">
                        {% if profile_form.address_complement.errors %}
                        <span class="help-block
                        {% if profile_form.address_complement.errors %}
                            text-danger small
                        {% endif %}
                    ">{{ profile_form.address_complement.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-12 col-md-3">
                    <div class="form-group">
                        <label for="{{profile_form.neighborhood.name}}">{{profile_form.neighborhood.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.neighborhood.errors %}
                        border border-danger
                        {% endif %}
                        " id="{{profile_form.neighborhood.name}}" name="{{profile_form.neighborhood.name}}"
                            value="{{ profile_form.neighborhood.value|default_if_none:"" }}">
                        <span class="help-block
                            {% if profile_form.neighborhood.errors %}
                            text-danger small
                            {% endif %}">{{ profile_form.neighborhood.errors.0 }}</span>

                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="form-group">
                        <label for="{{profile_form.city.name}}">{{profile_form.city.label}}</label>
                        <input type="text" class="form-control
                        {% if profile_form.city.errors %}
                        border border-danger
                        {% endif %}
                        " id="{{profile_form.city.name}}" name="{{profile_form.city.name}}"
                            value="{{ profile_form.city.value|default_if_none:"" }}">
                        {% if profile_form.city.errors %}
                        <span class="help-block
                        {% if profile_form.city.errors %}
                        text-danger small
                        {% endif %}">{{ profile_form.city.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="col-4 col-md-2">
                    <div class="form-group">
                        <label for="{{profile_form.state.name}}">{{profile_form.state.label}}</label>
                        <input type="text" class="form-control" id="{{profile_form.state.name}}"
                            name="{{profile_form.state.name}}"
                            value="{{ profile_form.state.value|default_if_none:"" }}">
                        {% if profile_form.state.errors %}
                        <span class="help-block 
                        {% if profile_form.state.errors %}
                            text-danger small
                        {% endif %}
                        ">{{ profile_form.state.errors.0 }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="row mt-3">
                <div class="col col-12 text-center">
                    <button class="btn btn-lg btn-primary" type="submit">Salvar</button>
                </div>
            </div>
        </form>
    </div>
</section>
<script>
    document.getElementById('{{profile_form.zip_code.name}}').addEventListener('blur', function (e) {
        var zip_code = document.getElementById('{{profile_form.zip_code.name}}').value;
        var url = 'https://viacep.com.br/ws/' + zip_code + '/json/';
        var xhr = new XMLHttpRequest();
        xhr.open('GET', url);
        xhr.onload = function () {
            if (xhr.status === 200) {
                var response = JSON.parse(xhr.responseText);
                document.getElementById('{{profile_form.address.name}}').value = response.logradouro;
                document.getElementById('{{profile_form.neighborhood.name}}').value = response.bairro;
                document.getElementById('{{profile_form.city.name}}').value = response.localidade;
                document.getElementById('{{profile_form.state.name}}').value = response.uf;
                document.getElementById('{{profile_form.address_number.name}}').focus();
            }
        };
        xhr.send();
    });
</script>
{% endblock %}

accounts/templates/reconfirmation.html
{% extends 'base.html' %}

{% block title %}Solicitar Confirmação de Conta{% endblock %}

{% block content %}
<form action="{% url 'accounts:reconfirmation' %}" method="post" class="form row p-4">
    <div class="col col-12">
        {% csrf_token %}
        <div class="row mb-4">
            <div class="col col-8 offset-2">
                <label for="email" class="form-label">Email de cadastro:</label>
                <input type="email" name="email" id="email" class="form-control" autofocus
                    placeholder="seu@email.com.br" required />
            </div>
        </div>
        <div class="row">
            <div class="col col-6 text-center">
                <input type="submit" value="Confirmar" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
{% endblock %}